services:
  - type: web
    name: trading-platform
    env: node
    buildCommand: npm install && npm run db:push -- --force && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
