services:
  - type: web
    name: trading-platform
    env: node
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
