services:
  - type: web
    name: trading-platform
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node ./dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
